development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: share-marks_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: share-marks_test
  pool: 5
